# Generated by Django 4.2.1 on 2023-05-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0003_timeunit_base_unit_instance_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeunit',
            name='base_unit_instance_names',
            field=models.CharField(blank=True, default='', max_length=800),
        ),
    ]
