# Generated by Django 4.2.1 on 2023-05-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0005_timeunit_base_unit_custom_lengths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeunit',
            name='base_unit_custom_lengths',
        ),
        migrations.RemoveField(
            model_name='timeunit',
            name='number_of_base',
        ),
        migrations.AddField(
            model_name='timeunit',
            name='length_cycle',
            field=models.CharField(default='1', max_length=800),
        ),
    ]
