# Generated by Django 4.2.1 on 2023-05-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0007_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=models.TextField(blank=True, max_length=800),
        ),
    ]
