# Generated by Django 4.2.1 on 2023-05-15 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0008_alter_event_event_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_format_name', models.CharField(max_length=200)),
                ('format_string', models.CharField(max_length=200)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasycalendar.calendar')),
                ('time_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasycalendar.timeunit')),
            ],
        ),
    ]
