# Generated by Django 4.2.1 on 2023-05-17 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0009_dateformat'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeunit',
            name='default_date_format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasycalendar.dateformat'),
        ),
    ]
