# Generated by Django 4.2.1 on 2023-05-18 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0011_displayconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='default_display_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fantasycalendar.displayconfig'),
        ),
    ]
