# Generated by Django 4.2.1 on 2023-05-22 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0012_calendar_default_display_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_bookmark_name', models.CharField(blank=True, max_length=200)),
                ('bookmark_iteration', models.IntegerField()),
                ('bookmark_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasycalendar.timeunit')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasycalendar.calendar')),
            ],
        ),
        migrations.AddField(
            model_name='displayconfig',
            name='default_date_bookmark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasycalendar.datebookmark'),
        ),
    ]
