# Generated by Django 4.2.1 on 2023-06-01 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fantasycalendar', '0013_datebookmark_displayconfig_default_date_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='default_display_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fantasycalendar.displayconfig'),
        ),
        migrations.AlterField(
            model_name='displayconfig',
            name='default_date_bookmark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasycalendar.datebookmark'),
        ),
        migrations.AlterField(
            model_name='timeunit',
            name='default_date_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasycalendar.dateformat'),
        ),
    ]
