# Generated by Django 4.2.1 on 2023-07-12 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0016_timeunit_secondary_date_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeunit',
            name='default_date_format',
            field=models.ForeignKey(blank=True, help_text='<span class="tooltip">?<span class="tooltip-text">The format for instances of this time unit to be displayed as most prominently, such as on the title of a calendar page</span></span>', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeunit_default_set', to='fantasycalendar.dateformat'),
        ),
        migrations.AlterField(
            model_name='timeunit',
            name='secondary_date_format',
            field=models.ForeignKey(blank=True, help_text='<span class="tooltip">?<span class="tooltip-text">The format for instances of this time unit to be displayed as in less prominent locations, often in groups underneath a parent unit, such as on individual boxes in a calendar page</span></span>', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeunit_secondary_set', to='fantasycalendar.dateformat'),
        ),
    ]
