# Generated by Django 4.2.1 on 2023-07-21 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0018_datebookmark_personal_bookmark_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayconfig',
            name='display_unit',
            field=models.ForeignKey(help_text='<span class="tooltip">?<span class="tooltip-text">The type of time unit to display by default</span></span>', on_delete=django.db.models.deletion.CASCADE, to='fantasycalendar.timeunit'),
        ),
        migrations.CreateModel(
            name='DisplayUnitConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.CharField(choices=[('iteration', 'Iteration'), ('formats', 'Date Formats'), ('none', 'Not Searchable')], default='iteration', help_text='<span class="tooltip">?<span class="tooltip-text">How to find a specific instance of this time unit on your calendar: by typing in an iteration number directly, by typing in a formatted date of a format you specify (or one of many formats you specify), or by no means at all</span></span>', max_length=32)),
                ('header_display_name_type', models.CharField(choices=[('default', 'Default Date Format'), ('secondary', 'Secondary Date Format'), ('other', 'Other Specified Date Format'), ('basic', 'No Date Format')], default='default', help_text='<span class="tooltip">?<span class="tooltip-text">How to determine the main header of your calendar page for this time unit: by using the time unit\'s default date format, by using its secondary format, by specifying some other format, or by using no format, generating something like "(time unit name) (iteration)"</span></span>', max_length=32)),
                ('base_unit_display_name_type', models.CharField(choices=[('default', 'Default Date Format'), ('secondary', 'Secondary Date Format'), ('other', 'Other Specified Date Format'), ('basic', 'No Date Format')], default='secondary', help_text='<span class="tooltip">?<span class="tooltip-text">How to determine the header of each cell in your calendar page for this time unit: by using the base time unit\'s default date format, by using its secondary format, by specifying some other format, or by using no format, generating something like "(base time unit name) (relative iteration)"</span></span>', max_length=32)),
                ('base_unit_other_date_format', models.ForeignKey(help_text='<span class="tooltip">?<span class="tooltip-text">The date format to use if "Other" is selected for the base unit display name type</span></span>', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fantasycalendar.dateformat')),
                ('display_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasycalendar.displayconfig')),
                ('header_other_date_format', models.ForeignKey(help_text='<span class="tooltip">?<span class="tooltip-text">The date format to use if "Other" is selected for the header display name type</span></span>', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fantasycalendar.dateformat')),
                ('searchable_date_formats', models.ManyToManyField(blank=True, help_text='<span class="tooltip">?<span class="tooltip-text">If search type is "Date Formats", these are the date formats to allow searching by; you will only see a single search bar on the calendar even if multiple formats are searchable, but the formats must all be distinct enough from each other for the system to tell which format was typed in</span></span>', to='fantasycalendar.dateformat')),
                ('time_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasycalendar.timeunit')),
            ],
        ),
        migrations.AddConstraint(
            model_name='displayunitconfig',
            constraint=models.UniqueConstraint(fields=('display_config', 'time_unit'), name='unique_display_config_time_unit'),
        ),
    ]
