# Generated by Django 4.2.1 on 2023-07-22 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0019_alter_displayconfig_display_unit_displayunitconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayunitconfig',
            name='base_unit_other_date_format',
            field=models.ForeignKey(blank=True, help_text='<span class="tooltip">?<span class="tooltip-text">The date format to use if "Other" is selected for the base unit display name type</span></span>', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fantasycalendar.dateformat'),
        ),
        migrations.AlterField(
            model_name='displayunitconfig',
            name='header_other_date_format',
            field=models.ForeignKey(blank=True, help_text='<span class="tooltip">?<span class="tooltip-text">The date format to use if "Other" is selected for the header display name type</span></span>', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fantasycalendar.dateformat'),
        ),
    ]
