# Generated by Django 4.2.1 on 2023-07-26 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0020_alter_displayunitconfig_base_unit_other_date_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayunitconfig',
            name='row_grouping_label_type',
            field=models.CharField(choices=[('none', 'No Labels'), ('names', 'Label Columns by Name'), ('numbers', 'Label Columns by Number'), ('counts', 'Label Rows by Count')], default='none', help_text='<span class="tooltip">?<span class="tooltip-text">The style of labeling to use for rows/columns if a row grouping time unit is specified: no labels, labels on each column with the name of the base unit of the row grouping time unit (e.g. Wednesday for a week), labels on each column with the number of the base unit of the row grouping time unit (e.g. 4 instead of Wednesday), or labels on each row that count the occurrences of the row grouping unit (Week 1, Week 2, etc.)</span></span>', max_length=32),
        ),
        migrations.AddField(
            model_name='displayunitconfig',
            name='row_grouping_time_unit',
            field=models.ForeignKey(blank=True, help_text='<span class="tooltip">?<span class="tooltip-text">An optional time unit that can be used to organize the calendar page into rows, e.g. many real life month calendar pages are grouped by one week per row; must have the same base unit as the page\'s time unit and a non-varying length cycle</span></span>', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fantasycalendar.timeunit'),
        ),
    ]
