# Generated by Django 4.2.1 on 2024-03-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0021_displayunitconfig_row_grouping_label_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=models.TextField(blank=True, help_text='<span class="tooltip">?<span class="tooltip-text">A description for this event</span></span>', max_length=4000),
        ),
    ]
