# Generated by Django 4.2.11 on 2024-04-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0022_alter_event_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='display_order',
            field=models.IntegerField(default=1, help_text='<span class="tooltip">?<span class="tooltip-text">The order in which this event will display on the calendar (and in menus); events with the same display order will  display in an unpredictable order relative to each other</span></span>'),
        ),
    ]
