# Generated by Django 4.2.11 on 2024-12-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0023_event_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='world_link_iteration',
            field=models.BigIntegerField(blank=True, default=None, help_text='<span class="tooltip">?<span class="tooltip-text">The bottom level time unit instance used to link to other calendars in this world; set this to an equivalent iteration for every calendar in the world to be linked, or leave it blank to leave the calendar unlinked</span></span>', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='display_order',
            field=models.IntegerField(default=1, help_text='<span class="tooltip">?<span class="tooltip-text">The order in which this event will display on the calendar (and in menus); events with the same display order will display in an unpredictable order relative to each other</span></span>'),
        ),
    ]
