# Generated by Django 4.2.11 on 2024-12-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0024_calendar_world_link_iteration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayunitconfig',
            name='max_events_per_instance',
            field=models.IntegerField(default=0, help_text='<span class="tooltip">?<span class="tooltip-text">The maximum number of events to show for a single time unit instance on your calendar page for this time unit; 0 for no limit</span></span>'),
        ),
        migrations.AddField(
            model_name='displayunitconfig',
            name='show_events',
            field=models.BooleanField(default=True, help_text='<span class="tooltip">?<span class="tooltip-text">Whether to show events on your calendar page for this time unit</span></span>'),
        ),
    ]
