# Generated by Django 4.2.11 on 2024-12-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0025_displayunitconfig_max_events_per_instance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayunitconfig',
            name='linked_instance_display_name_type',
            field=models.CharField(choices=[('default', 'Default Date Format'), ('secondary', 'Secondary Date Format'), ('other', 'Other Specified Date Format'), ('basic', 'No Date Format')], default='secondary', help_text='<span class="tooltip">?<span class="tooltip-text">How to determine the date format of linked time unit instances on your calendar page for this time unit: by using the linked time unit\'s default date format, by using its secondary format, or by using no format, generating something like "(linked time unit name) (relative iteration)"</span></span>', max_length=32),
        ),
        migrations.AddField(
            model_name='displayunitconfig',
            name='show_linked_instance_display_names',
            field=models.BooleanField(default=False, help_text='<span class="tooltip">?<span class="tooltip-text">Whether to show a date representation for each time unit instance linked from other calendars alongside bottom level time unit instances on your calendar page for this time unit</span></span>'),
        ),
        migrations.AddField(
            model_name='displayunitconfig',
            name='show_linked_instance_events',
            field=models.BooleanField(default=False, help_text='<span class="tooltip">?<span class="tooltip-text">Whether to show events from linked instances from other calendars on your calendar page for this time unit</span></span>'),
        ),
    ]
