# Generated by Django 4.2.11 on 2026-02-15 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0026_displayunitconfig_linked_instance_display_name_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visible',
            field=models.BooleanField(blank=True, default=True, help_text='<span class="tooltip">?<span class="tooltip-text">Whether this event should appear on the main calendar; will use group setting if not set and default to be visible if group is also not set</span></span>', null=True),
        ),
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_group_name', models.CharField(help_text='<span class="tooltip">?<span class="tooltip-text">The name of this event group</span></span>', max_length=200)),
                ('visible', models.BooleanField(default=True, help_text='<span class="tooltip">?<span class="tooltip-text">Whether the events in this group should appear on the main calendar</span></span>')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasycalendar.calendar')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fantasycalendar.eventgroup'),
        ),
    ]
