# Generated by Django 4.2.11 on 2026-04-11 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0027_event_visible_eventgroup_event_event_group'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='displayunitconfig',
            name='unique_display_config_time_unit',
        ),
        migrations.AddField(
            model_name='displayunitconfig',
            name='parent_time_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='displayunitconfig_parent_set', to='fantasycalendar.timeunit'),
        ),
        migrations.AlterField(
            model_name='displayunitconfig',
            name='time_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='displayunitconfig_set', to='fantasycalendar.timeunit'),
        ),
        migrations.AddConstraint(
            model_name='displayunitconfig',
            constraint=models.UniqueConstraint(fields=('display_config', 'time_unit', 'parent_time_unit'), name='unique_display_config_time_unit'),
        ),
    ]
