# Generated by Django 4.2.11 on 2026-04-14 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0028_remove_displayunitconfig_unique_display_config_time_unit_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='displayunitconfig',
            name='unique_display_config_time_unit',
        ),
        migrations.RemoveField(
            model_name='displayunitconfig',
            name='parent_time_unit',
        ),
        migrations.AddField(
            model_name='displayunitconfig',
            name='base_time_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='displayunitconfig_base_set', to='fantasycalendar.timeunit'),
        ),
        migrations.AddConstraint(
            model_name='displayunitconfig',
            constraint=models.UniqueConstraint(fields=('display_config', 'time_unit', 'base_time_unit'), name='unique_display_config_time_unit'),
        ),
    ]
