# Generated by Django 4.2.11 on 2026-04-17 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0030_remove_displayunitconfig_unique_display_config_time_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='displayunitconfig',
            old_name='base_unit_display_name_type',
            new_name='sub_unit_display_name_type',
        ),
        migrations.RenameField(
            model_name='displayunitconfig',
            old_name='base_unit_other_date_format',
            new_name='sub_unit_other_date_format',
        ),
    ]
