# Generated by Django 4.2.11 on 2026-04-17 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0031_rename_base_unit_display_name_type_displayunitconfig_sub_unit_display_name_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayunitconfig',
            name='row_grouping_time_unit',
            field=models.ForeignKey(blank=True, help_text='<span class="tooltip">?<span class="tooltip-text">An optional time unit that can be used to organize the calendar page into rows, e.g. many real life month calendar pages are grouped by one week per row; must have the same base unit as the page\'s sub unit and a non-varying length cycle</span></span>', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fantasycalendar.timeunit'),
        ),
        migrations.AlterField(
            model_name='displayunitconfig',
            name='sub_unit_display_name_type',
            field=models.CharField(choices=[('default', 'Default Date Format'), ('secondary', 'Secondary Date Format'), ('other', 'Other Specified Date Format'), ('basic', 'No Date Format')], default='secondary', help_text='<span class="tooltip">?<span class="tooltip-text">How to determine the header of each cell in your calendar page for this time unit: by using the sub time unit\'s default date format, by using its secondary format, by specifying some other format, or by using no format, generating something like "(sub time unit name) (relative iteration)"</span></span>', max_length=32),
        ),
        migrations.AlterField(
            model_name='displayunitconfig',
            name='sub_unit_other_date_format',
            field=models.ForeignKey(blank=True, help_text='<span class="tooltip">?<span class="tooltip-text">The date format to use if "Other" is selected for the sub unit display name type</span></span>', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fantasycalendar.dateformat'),
        ),
    ]
