# Generated by Django 4.2.11 on 2026-04-25 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0032_alter_displayunitconfig_row_grouping_time_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datebookmark',
            name='bookmark_sub_unit',
            field=models.ForeignKey(blank=True, help_text='<span class="tooltip">?<span class="tooltip-text">The sub time unit to use for the display page this bookmark points to</span></span>', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datebookmark_sub_set', to='fantasycalendar.timeunit'),
        ),
    ]
