# Generated by Django 4.2.11 on 2026-04-26 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0033_datebookmark_bookmark_sub_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayunitconfig',
            name='block_grouping_time_unit',
            field=models.ForeignKey(blank=True, help_text='<span class="tooltip">?<span class="tooltip-text">An optional time unit that can be used to organize the calendar page into blocks, e.g. many real life year calendar pages are blocked by month; must have the page\'s sub unit as one of its own sub units</span></span>', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fantasycalendar.timeunit'),
        ),
    ]
