# Generated by Django 4.2.11 on 2026-05-03 17:02

from django.db import migrations, models
import django.db.models.deletion

TEMPORARY_DEFAULT = 1


def forwards(apps, _):
    DisplayConfig = apps.get_model('fantasycalendar', 'DisplayConfig')
    DisplayUnitConfig = apps.get_model('fantasycalendar', 'DisplayUnitConfig')
    display_configs = DisplayConfig.objects.all()
    for display_config in display_configs:
        display_config.default_display_unit_config = DisplayUnitConfig.objects.filter(
            display_config_id=display_config.pk).order_by("time_unit").last()
        display_config.save()

def backwards(apps, _):
    DisplayConfig = apps.get_model('fantasycalendar', 'DisplayConfig')
    DisplayUnitConfig = apps.get_model('fantasycalendar', 'DisplayUnitConfig')
    display_configs = DisplayConfig.objects.all()
    for display_config in display_configs:
        display_config.default_display_unit_config = DisplayUnitConfig.objects.get(pk=TEMPORARY_DEFAULT)
        display_config.save()


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0034_displayunitconfig_block_grouping_time_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='displayconfig',
            name='display_unit',
        ),
        migrations.RemoveField(
            model_name='displayconfig',
            name='nest_level',
        ),
        migrations.AddField(
            model_name='displayconfig',
            name='default_display_unit_config',
            field=models.ForeignKey(default=TEMPORARY_DEFAULT, help_text='<span class="tooltip">?<span class="tooltip-text">The time unit page to show by default</span></span>', on_delete=django.db.models.deletion.CASCADE, to='fantasycalendar.displayunitconfig'),
            preserve_default=False,
        ),
        migrations.RunPython(forwards, backwards)
    ]
