# Generated by Django 4.2.11 on 2026-05-03 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0035_remove_displayconfig_display_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayconfig',
            name='default_display_unit_config',
            field=models.ForeignKey(help_text='<span class="tooltip">?<span class="tooltip-text">The time unit page to show by default</span></span>', null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasycalendar.displayunitconfig'),
        ),
    ]
