# Generated by Django 4.2.11 on 2026-05-16 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0036_alter_displayconfig_default_display_unit_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayunitconfig',
            name='block_unit_page',
            field=models.ForeignKey(blank=True, help_text='<span class="tooltip">?<span class="tooltip-text">The time unit page to navigate to when the block label is clicked; if blank, the block label will not be clickable</span></span>', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fantasycalendar.displayunitconfig'),
        ),
        migrations.AddField(
            model_name='displayunitconfig',
            name='row_unit_page',
            field=models.ForeignKey(blank=True, help_text='<span class="tooltip">?<span class="tooltip-text">The time unit page to navigate to when the row label is clicked; if blank, the row label will not be clickable</span></span>', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fantasycalendar.displayunitconfig'),
        ),
        migrations.AddField(
            model_name='displayunitconfig',
            name='sub_unit_page',
            field=models.ForeignKey(blank=True, help_text='<span class="tooltip">?<span class="tooltip-text">The time unit page to navigate to when the sub unit header is clicked; if blank, the sub unit header will not be clickable</span></span>', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fantasycalendar.displayunitconfig'),
        ),
    ]
