# Generated by Django 4.2.11 on 2026-05-30 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0038_alter_displayconfig_default_display_unit_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayconfig',
            name='default_date_bookmark',
            field=models.ForeignKey(blank=True, help_text='<span class="tooltip">?<span class="tooltip-text">The date to show by default when this display configuration is initially loaded</span></span>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fantasycalendar.datebookmark'),
        ),
    ]
