# Generated by Django 4.2.11 on 2026-06-02 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0039_alter_displayconfig_default_date_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayunitconfig',
            name='block_grouping_time_unit',
            field=models.ForeignKey(blank=True, help_text='<span class="tooltip">?<span class="tooltip-text">An optional time unit that can be used to organize the calendar page into blocks, e.g. many real life year calendar pages are blocked by month; must have the page\'s sub unit as one of its own sub units</span></span>', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fantasycalendar.timeunit'),
        ),
        migrations.AlterField(
            model_name='displayunitconfig',
            name='row_grouping_time_unit',
            field=models.ForeignKey(blank=True, help_text='<span class="tooltip">?<span class="tooltip-text">An optional time unit that can be used to organize the calendar page into rows, e.g. many real life month calendar pages are grouped by one week per row; must have the same base unit as the page\'s sub unit and a non-varying length cycle</span></span>', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fantasycalendar.timeunit'),
        ),
        migrations.AlterField(
            model_name='timeunit',
            name='base_unit',
            field=models.ForeignKey(blank=True, help_text='<span class="tooltip">?<span class="tooltip-text">The type of time unit that this time unit consists of,  e.g. "Year" could have a base unit of "Month"</span></span>', null=True, on_delete=django.db.models.deletion.PROTECT, to='fantasycalendar.timeunit'),
        ),
    ]
