# Generated by Django 4.2.11 on 2026-06-06 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0040_alter_displayunitconfig_block_grouping_time_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayunitconfig',
            name='header_other_date_format',
            field=models.ForeignKey(blank=True, help_text='<span class="tooltip">?<span class="tooltip-text">The date format to use if "Other" is selected for the header display name type</span></span>', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fantasycalendar.dateformat'),
        ),
        migrations.AlterField(
            model_name='displayunitconfig',
            name='sub_unit_other_date_format',
            field=models.ForeignKey(blank=True, help_text='<span class="tooltip">?<span class="tooltip-text">The date format to use if "Other" is selected for the sub unit display name type</span></span>', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fantasycalendar.dateformat'),
        ),
        migrations.AlterField(
            model_name='timeunit',
            name='default_date_format',
            field=models.ForeignKey(blank=True, help_text='<span class="tooltip">?<span class="tooltip-text">The format for instances of this time unit to be displayed as most prominently, such as on the title of a calendar page</span></span>', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeunit_default_set', to='fantasycalendar.dateformat'),
        ),
        migrations.AlterField(
            model_name='timeunit',
            name='secondary_date_format',
            field=models.ForeignKey(blank=True, help_text='<span class="tooltip">?<span class="tooltip-text">The format for instances of this time unit to be displayed as in less prominent locations, often in groups underneath a parent unit, such as on individual boxes in a calendar page</span></span>', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeunit_secondary_set', to='fantasycalendar.dateformat'),
        ),
    ]
