# Generated by Django 4.2.11 on 2026-06-06 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0041_alter_displayunitconfig_header_other_date_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayconfig',
            name='default_display_unit_config',
            field=models.ForeignKey(help_text='<span class="tooltip">?<span class="tooltip-text">The time unit page to show by default</span></span>', null=True, on_delete=django.db.models.deletion.RESTRICT, to='fantasycalendar.displayunitconfig'),
        ),
        migrations.AlterField(
            model_name='timeunit',
            name='base_unit',
            field=models.ForeignKey(blank=True, help_text='<span class="tooltip">?<span class="tooltip-text">The type of time unit that this time unit consists of,  e.g. "Year" could have a base unit of "Month"</span></span>', null=True, on_delete=django.db.models.deletion.RESTRICT, to='fantasycalendar.timeunit'),
        ),
    ]
