# Generated by Django 4.2.11 on 2026-06-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0042_alter_displayconfig_default_display_unit_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='navigable',
            field=models.BooleanField(blank=True, default=False, help_text='<span class="tooltip">?<span class="tooltip-text">Whether this event should should have a link under the bookmarks dropdown; will use group setting if not set and default to be not navigable if group is also not set</span></span>', null=True),
        ),
        migrations.AddField(
            model_name='eventgroup',
            name='navigable',
            field=models.BooleanField(default=False, help_text='<span class="tooltip">?<span class="tooltip-text">Whether the events in this group should have a link under the bookmarks dropdown</span></span>'),
        ),
    ]
