# Generated by Django 5.2.16 on 2026-08-01 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0043_event_navigable_eventgroup_navigable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_iteration', models.IntegerField(help_text='<span class="tooltip">?<span class="tooltip-text">The instance of the specified time unit type for this note to link to</span></span>')),
                ('note_text', models.TextField(blank=True, help_text='<span class="tooltip">?<span class="tooltip-text">The content of this note</span></span>', max_length=4000)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasycalendar.calendar')),
                ('note_creator', models.ForeignKey(blank=True, help_text='<span class="tooltip">?<span class="tooltip-text">The creator of this note</span></span>', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('note_unit', models.ForeignKey(help_text='<span class="tooltip">?<span class="tooltip-text">The type of time unit that this note is for</span></span>', on_delete=django.db.models.deletion.CASCADE, to='fantasycalendar.timeunit')),
            ],
        ),
    ]
