# Generated by Django 5.2.16 on 2026-08-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0044_usernote'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernote',
            name='public',
            field=models.BooleanField(default=False, help_text='<span class="tooltip">?<span class="tooltip-text">Whether this note is viewable by other people</span></span>'),
        ),
    ]
