# Generated by Django 5.2.16 on 2026-09-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasycalendar', '0045_usernote_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='world',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
